version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: sistema_tickets_app
    ports:
      - "8080:80"
    volumes:
      # Mapeamos la carpeta backend dentro del servidor web de Apache (/var/www/html)
      - ./backend:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=tickets_db
      - DB_USER=root
      - DB_PASS=secret
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: sistema_tickets_db
    restart: always
    environment:
      MYSQL_DATABASE: tickets_db
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sistema_tickets_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
    depends_on:
      - db

volumes:
  db_data: