services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: php -S 0.0.0.0:8000 -t public public/index.php
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
  frontend:
    image: php:8.3-cli

    working_dir: /frontend

    command: php -S 0.0.0.0:3000 -t /frontend

    ports:
      - "3000:3000"

    volumes:
      - ./Frontend:/frontend


  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "--password=${DB_ROOT_PASSWORD}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: